spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.username=********@gmail.com
spring.mail.password=ylyi rrdm piut smbm
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

rupee.sign=VND

vnpay.tmnCode=I18E26XA
vnpay.hashSecret=5LR6M4GZ13G9RHST7ADRZDVFKJXRJJRE
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8080/payment/vnpay-return
vnpay.version=2.1.0
vnpay.command=pay
vnpay.orderType=other

gemini.api.key=AIzaSyBVaiub4gy5PjGmUUcQ84pM7FJHCySXYCI
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
gemini.max-tokens=1024

store.name=SHOPPKTH
store.phone=0393846572
store.email=support@shoppkth.com.vn
store.address=20 Hồ Tùng Mậu, Cầu Giấy, Mai Dịch,Hà Nội