# ===================== DATABASE (H2 on Render) =====================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true

# ===================== MAIL CONFIG =====================
spring.mail.host=smtp.gmail.com
spring.mail.username=********@gmail.com
spring.mail.password=ylyi rrdm piut smbm
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===================== UPLOAD =====================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ===================== OTHER CONFIG =====================
rupee.sign=VND

# ===================== VNPAY CONFIG =====================
vnpay.tmnCode=I18E26XA
vnpay.hashSecret=5LR6M4GZ13G9RHST7ADRZDVFKJXRJJRE
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8080/payment/vnpay-return
vnpay.version=2.1.0
vnpay.command=pay
vnpay.orderType=other

# ===================== RENDER PORT =====================
server.port=${PORT:8080}
